name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - run: rustup target add riscv64gc-unknown-none-elf
    - run: cargo fmt --all -- --check
    - run: cargo clippy -- -D warnings
    - run: cargo build
    - run: cargo build --release
