name: CI

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@nightly
    - run: rustup component add rustfmt clippy
    - run: rustup target add riscv64gc-unknown-none-elf
    - run: make fmt-check
    - run: make clippy
    - run: make build
    - run: MODE=release make build
